### ISSUE TITLE
Does ReiNand work with 3ds update 11.7.0-40

### ISSUE THREAD

**Issue by CJ3510** [Reisyukaku/ReiNand#92] opened 2018-06-25 14:16 UTC
I still have 10.4 downloaded on my 3ds but, I would like to update to 11.7.0-40. I am just nervous that my 3ds could break. I really want to be able to use internet services again. So, if someone can answer my question it would be greatly appreciated.

**Comment by Reisyukaku** [comment] 2018-06-27 00:11
I dont see any reason why things would break. I made this pretty future proof.

**Comment by CrimsonMaple** [comment] 2018-06-27 01:24
Duplicate of #88 
Both versions use the same firmware.bin

**Closed as completed** 2018-06-27 01:25 UTC
