### ISSUE TITLE
Amiibo non working ReiNand 11.0.0-33E

### ISSUE THREAD

**Issue by FunkyArt** [Reisyukaku/ReiNand#55] opened 2016-05-22 16:28 UTC
Hello ! :D
I've got a problem, i can't use my amiibos on my New 3ds Emunand 11.0.0-33E. I'm trying every single game and none of my 9 amiibos are working. They are not detected by the new 3ds screen... And my amiibos are working, i'm using them with my wii u !

**Comment by Reisyukaku** [comment] 2016-05-22 23:34
I dont have any amiibos to test that but my cfw doesnt touch any amiibo services or games, so thats odd.

**Comment by FunkyArt** [comment] 2016-05-23 19:00
I don't understand, i could use them before in the 10.7 version ! D:

**Comment by cYcLoNeAUT** [comment] 2016-05-23 22:31
I can confirm amiibo´s working on 11.0.0-33E N3DS Emunand and Rei 4.1. Tested with SSB 3DS and Marth amiibo. 
Maybe you just forgot to switch wireless on in settings.

**Comment by FunkyArt** [comment] 2016-05-24 18:49
I've switched it, this is why i don't understand ! D:

**Comment by Reisyukaku** [comment] 2016-05-24 19:53
ive had a friend also confirm it works for them. Maybe you just got a bad update?

**Comment by FunkyArt** [comment] 2016-05-24 20:23
I don't understand, i've downgraded to 10.7, and it doesn't work anymore... Should i try to downgrade to 9.2, then update to 10.7 ? I can't see if it is the NFC chip of my n3ds that is not working, because my sysnand is in 9.2...

**Comment by Reisyukaku** [comment] 2016-05-25 00:29
You could try using sys updater with a full 11.0 pack i suppose. (from emunand or where ever is giving the issue)

**Comment by FunkyArt** [comment] 2016-05-25 04:43
I've tried it, I've downgraded my emunand to 9.2, then I've updated to 11.0, and always the same problem!

**Comment by Rohul1997** [comment] 2016-05-25 09:20
Someone had the same problem as this and after opening it up and reseating the nfc it worked.

**Comment by FunkyArt** [comment] 2016-05-25 12:19
Reseating the nfc chip? How? I know how to open the 3ds, but I know where is located the nfc chip?

**Comment by Reisyukaku** [comment] 2016-05-25 18:43
@FunkyArt Under the bottom LCD, you'll see a paper thin thing, thats the NFC sensor. Try messing with that, but I warn you if you've never taken apart an N3DS, you could permanently damage the system if you dont unclasp things properly and all that. So lookup teardown vids or something first.

**Comment by FunkyArt** [comment] 2016-05-27 16:40
My screwdriver made unusable 4 of the 6 screw, so i'm screwed... Thank you for helping me during all these days, but i don't know what to do anymore... I thought of updating my sysnand to 9.3, then see if amiibos are working, and if not downgrading to 9.2, but i don't think it will change something...

**Comment by Reisyukaku** [comment] 2016-05-27 19:12
rip. Well ill close this for now since its a hardware issue anyways.

**Closed as completed by Reisyukaku** 2016-05-27 19:12 UTC
